### ISSUE TITLE
Generate New Release Request

### ISSUE THREAD

**Issue by mr-pmillz** [projectdiscovery/gologger#25]
Can you guys generate a new release please?
The TimeStamp() method is missing from the current latest release but is shown in the [basic-example](https://github.com/projectdiscovery/gologger/blob/master/examples/basic/basic.go) and exists in the latest codebase.

Cool project, much thanks.

**Comment by Mzack9999** [comment]
Indirectly fixed with https://github.com/projectdiscovery/gologger/issues/27
