### ISSUE TITLE
This module broke chaos

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [projectdiscovery/gologger#9]
Hello there!
I just tried to pull the newest release of `chaos` from its corresponding git repo but during compilation it just threw some nasty errors at me. I believe that you removed some methods that go would have been happy to find, but unfortunately it didn't. Tbh I didn't dig down the rabbit hole but I'm certain that it has to be something with the code here.
Cheers,
0x5ECF4ULT

Go version:
`go version go1.15.5 linux/amd64`

Command ran:
`GO111MODULE=on go get -u github.com/projectdiscovery/chaos-client/cmd/chaos@v0.1.6`

**Comment by bauthard** [comment]
@0x5ECF4ULT right command to install is `GO111MODULE=on go get -v github.com/projectdiscovery/chaos-client/cmd/chaos`

**Comment by 0x5ECF4ULT** [comment]
Resolved. That's weird... I used that exact command in the first place and it didn't work, so I thought specifying a version might help.
Closing
